// <auto-generated />
namespace cointoss.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddBetId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBetId));
        
        string IMigrationMetadata.Id
        {
            get { return "201308301810355_AddBetId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
