// <auto-generated />
namespace cointoss.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddInitialGuess : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddInitialGuess));
        
        string IMigrationMetadata.Id
        {
            get { return "201308272139372_AddInitialGuess"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
